const WORLD_CROPS = [

  // ─── CEREALS & GRAINS ───────────────────────────
  "Wheat",
  "Rice (Paddy)",
  "Corn / Maize",
  "Barley",
  "Oats",
  "Sorghum",
  "Pearl Millet",
  "Rye",
  "Triticale",
  "Buckwheat",
  "Quinoa",
  "Amaranth",
  "Teff",
  "Fonio",
  "Spelt",

  // ─── LEGUMES & PULSES ───────────────────────────
  "Soybean",
  "Chickpea",
  "Lentil",
  "Green Pea",
  "Black-Eyed Pea",
  "Kidney Bean",
  "Mung Bean",
  "Pigeon Pea",
  "Fava Bean",
  "Groundnut / Peanut",
  "Adzuki Bean",
  "Lupine",

  // ─── ROOT & TUBER CROPS ─────────────────────────
  "Potato",
  "Sweet Potato",
  "Cassava",
  "Yam",
  "Taro",
  "Sugar Beet",
  "Turnip",
  "Parsnip",
  "Radish",
  "Carrot",
  "Celeriac",
  "Kohlrabi",

  // ─── CASH CROPS ─────────────────────────────────
  "Sugarcane",
  "Cotton",
  "Tobacco",
  "Jute",
  "Flax / Linseed",
  "Hemp",
  "Sisal",
  "Rubber Tree",
  "Indigo",

  // ─── OILSEED CROPS ──────────────────────────────
  "Sunflower",
  "Canola / Rapeseed",
  "Sesame",
  "Safflower",
  "Mustard",
  "Castor Bean",
  "Oil Palm",
  "Coconut",
  "Olive",

  // ─── VEGETABLES ─────────────────────────────────
  "Tomato",
  "Onion",
  "Garlic",
  "Cabbage",
  "Cauliflower",
  "Broccoli",
  "Spinach",
  "Lettuce",
  "Cucumber",
  "Pumpkin",
  "Zucchini",
  "Eggplant / Brinjal",
  "Bell Pepper",
  "Chilli Pepper",
  "Okra / Lady Finger",
  "Asparagus",
  "Celery",
  "Leek",
  "Artichoke",
  "Bitter Gourd",
  "Bottle Gourd",
  "Snow Peas",
  "Brussels Sprouts",
  "Kale",
  "Swiss Chard",
  "Beetroot",

  // ─── FRUITS ─────────────────────────────────────
  "Banana",
  "Mango",
  "Papaya",
  "Pineapple",
  "Watermelon",
  "Cantaloupe Melon",
  "Strawberry",
  "Grapes / Vineyard",
  "Apple",
  "Orange / Citrus",
  "Lemon",
  "Avocado",
  "Guava",
  "Lychee",
  "Peach",
  "Pear",
  "Plum",
  "Cherry",
  "Kiwifruit",
  "Pomegranate",
  "Fig",
  "Date Palm",
  "Jackfruit",
  "Durian",
  "Blueberry",
  "Raspberry",
  "Passion Fruit",

  // ─── PLANTATION / TREE CROPS ────────────────────
  "Coffee",
  "Tea",
  "Cocoa",
  "Vanilla",
  "Cardamom",
  "Black Pepper",
  "Cinnamon",
  "Clove",
  "Nutmeg",
  "Cashew",
  "Almond",
  "Walnut",
  "Pistachio",
  "Macadamia",
  "Hazelnut",
  "Bamboo",

  // ─── FORAGE & FODDER CROPS ──────────────────────
  "Alfalfa",
  "Clover",
  "Ryegrass",
  "Bermuda Grass",
  "Napier Grass",
  "Sudan Grass",

  // ─── SPICES & HERBS ─────────────────────────────
  "Turmeric",
  "Ginger",
  "Cumin",
  "Coriander",
  "Fenugreek",
  "Fennel",
  "Basil",
  "Mint",
  "Thyme",
  "Oregano",
  "Rosemary",
  "Saffron",
  "Lemongrass",

  // ─── FIBER CROPS ────────────────────────────────
  "Kenaf",
  "Ramie",
  "Kapok",
  "Agave",

  // ─── BIOENERGY & INDUSTRIAL CROPS ───────────────
  "Jatropha",
  "Switchgrass",
  "Miscanthus",
  "Sweet Sorghum",
  "Moringa",

];